# GENRES
genre_list = ["techno", "house", "electro", "jungle", "drum & bass", "ambient", "new age", "vaporwave", "gabber", "trance", "drone", "industrial", "trap", "deconstructed club", "glitch", "avant garde", "hyperpop", "dub", "noise", "EBM", "classical", "chipmusic", "hardstyle", "footwork", "garage", "chillout", "minimal wave", "jazz"]

# KEYS
key_list = ["C major", "Db major", "D major", "Eb major", "E major", "F major", "F# major", "Gb major", "G major", "Ab major", "A major", "Bb major", "B major", "C minor", "C# minor", "D minor", "Eb minor", "D# minor", "E minor", "F minor", "F# minor", "G minor", "G# minor", "A minor", "Bb minor", "B minor"]

# PITCHES (CORRESPONDING TO KEYS IN KEY_LIST)
pitch_list = ["C D E F G A B", "Db Eb F Gb Ab Bb C", "D E F# G A B C#", "Eb F G Ab Bb C D", "E F# G# A B C# D#", "F G A Bb C D E", "F# G# A# B C# D# E#", "Gb Ab Bb Cb Db Eb F", "G A B C D E F#", "Ab Bb C Db Eb F G", "A B C# D E F# G#", "Bb C D Eb F G A", "B C# D# E F# G# A#", "C D Eb F G Ab Bb", "C# D# E F# G# A B", "D E F G A Bb C", "Eb F Gb Ab Bb Cb Db", "D# E# F# G# A# B C#", "E F# G A B C D", "F G Ab Bb C Db Eb", "F# G# A B C# D E", "G A Bb C D Eb F", "G# A# B C# D# E F#", "A B C D E F G", "Bb C Db Eb F Gb Ab", "B C# D# E F# G# A#"]

# SYSTEM 0 : BIG RIG (CIRKLON OR NERDSEQ OR TELETYPE)
# SYSTEM 1 : MIDI DEVICES (CIRKLON OR NERDSEQ)
# SYSTEM 2 : SOUND TOYS (NO SEQUENCER)
# SYSTEM 3 : STANDALONE (NO SEQUENCER)
# SYSTEM 4 : HIGH LEVEL (CIRKLON OR NERDSEQ OR TELETYPE OR NO SEQUENCER)
system_list = [ 
	["General CV", "Entity Bass Drum Synthesizer", "Plaits", "Zero Point Oscillator", "Chainsaw", "Squid Salmple", "Piston Honda", "SID Guts", "SID Guts Deluxe", "FMVDO", "Hertz Donut", "Akemie's Castle", "Tyme Sefari MK2", "Ataraxic Translatron", "Loquelic Iteritas", "Basimilus Iteritas Alter", "Pico Drums", "Gieskes No Drums", "Crater", "M303", "ER301", "Game Boy", "NES", "Sega Genesis", "Nord Micro Modular", "Plinky", "RE-303", "Juteon Shonen Bassboy+", "TR09"], 
	["Game Boy", "NES", "Sega Genesis", "Nord Micro Modular", "RE-303", "Juteon Shonen Bassboy+", "TR09"], 
	["Paripi Destroyer", "PO32 Tonic", "PO33 KO", "Plinky", "Korg NTS-1"], 
	["LSDJ", "Nanoloop 2", "Nanoloop Mono", "Norns", "Nord Micro Modular", "PO33 KO", "Plinky"],
	["wavetables", "vocals", "samples", "supersaws", "hoovers", "breakbeats", "prominent percussive elements", "white noise", "field recordings", "reverb", "delay", "repetition"]
]

# SEQUENCERS
# CORRESPONDING TO SYSTEM INTEROPERABILITY
sequencer_list = [
	["Cirklon", "Nerdseq", "Teletype"],
	["Cirklon", "Nerdseq"],
	["none"],
	["none"],
	["Cirklon", "Nerdseq", "Teletype", "none"]
]

# ACTIONS
action_list = ["think", "feel", "sound", "crumble", "explode", "collapse", "grow", "evolve", "transform", "build", "shrink", "echo", "disintegrate", "crackle", "sparkle", "bloom", "stretch", "bubble", "spread", "wander", "establish itself", "glow", "taste", "smell", "hurt", "move", "erode", "wither", "drip", "melt", "multiply", "rise", "shimmer", "crumble", "come into focus", "catch you by surprise", "activate"]

# OBJECTS
thing_list = ["fire", "ice", "concrete", "a forest", "the desert", "architecture", "water", "air", "the club", "a civilization", "steel", "sand", "glass", "a flower", "plastic", "oil", "lightning", "electricity", "a warehouse", "a field", "a river", "a lake", "a meadow", "the mountains", "the sky", "the dark", "a mind", "a bomb", "electronics", "nature", "an animal", "a figure", "a party", "a dying star", "an organism", " a lifeform", "a tree", "the dirt", "a stone", "a city", "a love"]

# CONTEXTS
context_list = ["from your childhood", "from a half-remembered dream", "from a place you've never been", "from the best night of your life", "from the worst night of your life", "generated by an AI", "described in an ancient manuscript", "from a place that doesn't exist", "from the deepest parts of the web", "as described by a child", "caught in your throat", "in the pit of your stomach", "from a nightmare", "on the ocean floor", "buried deep underground"]
